### ISSUE TITLE
Can't select ingredients

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#11]
A recent update (perhaps preferencing the most popular selection when typing an ingredient?) has made it so that ingredient autofill is basically nonfunctional. If I type "Cam" Campari comes up in the suggestion list but if I either press enter or actually select "Campari" with the mouse, nothing populates the ingredient box. This is a regression which means all data entry is completely manual (no autofill).

**Comment by gthole** [comment]
Yikes!  I'll take a look.  What browser are you using?

It might well be the custom auto-complete component too.

**Comment by gthole** [comment]
I pushed a change that should definitely fix the mouse selection and hopefully fixes the "press enter".  Give it a try and let me know?

**Comment by jelloeggy** [comment]
It is definitely better! I can now select ingredients with the mouse and "press enter" works as well. I think that it used to work that if you were on the ingredient in the drop down and press "tab" it would autocomplete the word, which still doesn't work, but having "enter" work might be sufficient. I'll do some data entry now and report back.

**Comment by jelloeggy** [comment]
Yes, it is missing the tab autofill but its definitely better in every other way. Just requires changing your typing workflow to use enter.

**Comment by gthole** [comment]
Tab autofill restored and deployed.  If you press tab, it autocompletes the value and moves focus to the next input element (whereas pressing return or mouse clicking will just autocomplete the value without moving the focus.)

Lemme know if that's better!

**Comment by jelloeggy** [comment]
Still does not work with tab (i.e. no autocomplete). I logged out and back in but did not refresh my whole browser. I am on Chrome 71.0.3578.127.

**Comment by gthole** [comment]
Hrm.  The deployed site works for me on both Firefox and Chrome.  You should only have to reload the page to get the latest deployment UI code.

**Comment by jelloeggy** [comment]
I must not have refreshed correctly before? In any case, closing the browser fully and reopening revealed the fixed version and it's perfect now. Very responsive as well.

**Comment by gthole** [comment]
🎉!
Also this should fix the flashing autocomplete bug too, since I replaced the whole component to do it.
